[package]
name = "rank-api"
version = "0.1.0"
authors = ["Antonio <toninho0007@yahoo.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = "0.4.4"
postgres = "0.17.2"